name: Svein Pipeline

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
      - staging
    paths-ignore:
      - '**.md'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm
    - name: Installing dependencies
      run: npm ci
    - name: Building project
      run: npm run build
    - name: Running tests
      run: npm run test
